/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio2.vista;

import Ejercicio2.Controlador.OficinaController;
import Ejercicio2.Controlador.TicketController;
import Ejercicio2.vista.ModeloTabla.ModeloTablaTickets;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author JavierSarango
 */
public class frm_RegTicket extends javax.swing.JDialog {

    private OficinaController of = new OficinaController();
    private TicketController tc = new TicketController();
    private SimpleDateFormat st = new SimpleDateFormat("yyyy-MM-dd");
    private ModeloTablaTickets mtt = new ModeloTablaTickets();
    int f = -1;

    /**
     * Creates new form frm_RegTicket
     */
    public frm_RegTicket(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);

        initComponents();
        lblRestantes.setText(String.valueOf(tc.getColaticket().getSize()));
        limpiar();
    }

    public void limpiar() {
        txtNombreCliente.setText("");
        txtApeCliente.setText("");
        txtTramite.setText("");
        txtPrecio.setText("");
        tc.setTicket(null);
        cargarTabla();

    }

    public void cargarTabla() {
        mtt.setLista(tc.getListaTicket().getLista());
        tblTickets.setModel(mtt);
        tblTickets.updateUI();

    }

    public void guardar() {
        if (txtNombreCliente.getText().trim().isEmpty() || txtApeCliente.getText().trim().isEmpty()
                || txtPrecio.getText().trim().isEmpty() || txtTramite.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene los campos vacíos", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {

                Date fecha = jdateFechaTurno.getDate();
                String d = st.format(fecha);
                tc.getTicket().setNomCliente(txtNombreCliente.getText().trim());
                tc.getTicket().setApeCliente(txtApeCliente.getText().trim());
                tc.getTicket().setServicio(txtTramite.getText().trim());
                tc.getTicket().setFecha(d);
                tc.getTicket().setPrecio(Double.parseDouble(txtPrecio.getText().trim()));
                if (tc.guardar(txtNombreCliente.getText().trim(),
                        txtApeCliente.getText().trim(), d,
                        txtTramite.getText().trim(),Double.parseDouble(txtPrecio.getText().trim()))) {
                    JOptionPane.showMessageDialog(null, "Guardado", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    lblRestantes.setText(String.valueOf(tc.getColaticket().getSize()) );
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo guardar", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        limpiar();
    }
    public void atender(){
        try {
            f = tblTickets.getSelectedRow();
           tc.borradoLogico(f);
           JOptionPane.showMessageDialog(null, "Usuario Atendido", "Éxito", JOptionPane.INFORMATION_MESSAGE);
           lblRestantes.setText(String.valueOf(Integer.parseInt(lblRestantes.getText())-1));
           limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo atender", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApeCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTramite = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnAgendar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jdateFechaTurno = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTickets = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lblRestantes = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Registro de Tickets");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(118, 6, 117, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingreso de Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.setLayout(null);

        jLabel2.setText("Nombre Cliente:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 30, 100, 30);
        jPanel2.add(txtNombreCliente);
        txtNombreCliente.setBounds(130, 30, 160, 30);

        jLabel3.setText("Apellido Cliente:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 70, 90, 30);
        jPanel2.add(txtApeCliente);
        txtApeCliente.setBounds(130, 70, 160, 30);

        jLabel5.setText("Trámite:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 120, 80, 30);
        jPanel2.add(txtTramite);
        txtTramite.setBounds(130, 120, 160, 30);

        jLabel4.setText("Costo:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 230, 50, 30);
        jPanel2.add(txtPrecio);
        txtPrecio.setBounds(130, 230, 160, 30);

        btnAgendar.setText("Agendar");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgendar);
        btnAgendar.setBounds(20, 360, 100, 30);

        jLabel6.setText("Fecha:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 170, 50, 30);
        jPanel2.add(jdateFechaTurno);
        jdateFechaTurno.setBounds(130, 170, 160, 30);

        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(180, 360, 100, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 320, 430);

        tblTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTickets);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(350, 60, 470, 360);

        jLabel7.setText("Restantes:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(560, 20, 70, 20);

        lblRestantes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(lblRestantes);
        lblRestantes.setBounds(650, 10, 20, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("/ 20");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(680, 6, 40, 40);

        jButton2.setText("Atender");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(690, 450, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 830, 530);

        setSize(new java.awt.Dimension(848, 535));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        atender();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_RegTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_RegTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_RegTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_RegTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_RegTicket(new javax.swing.JDialog(), true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdateFechaTurno;
    private javax.swing.JLabel lblRestantes;
    private javax.swing.JTable tblTickets;
    private javax.swing.JTextField txtApeCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTramite;
    // End of variables declaration//GEN-END:variables
}
