/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ejercicio2.vista;

import Ejercicio2.Controlador.OficinaController;
import Ejercicio2.vista.ModeloTabla.ModeloTablaOficinas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author Javier
 */
public class frm_Oficina extends javax.swing.JDialog {
    private OficinaController ofc = new OficinaController();
    private ModeloTablaOficinas mto = new ModeloTablaOficinas();
    /**
     * Creates new form VentaTickets
     */
    public frm_Oficina(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        poputTable();
       Limpiar();
    }
    public void cargarTablaOficina(){
    mto.setLista(ofc.getListaOficina().getLista());
    tblOficina.setModel(mto);
    tblOficina.updateUI();
    
    }
    public void Limpiar(){
    txtApeEncargado.setText("");
    txtNomEncargado.setText("");
    ofc.setOficina(null);
    cargarJCombox();
    cargarTablaOficina();
    
    }
    public void cargarJCombox (){
    cbxServicios.removeAllItems();
    cbxServicios.addItem("Abrir Cuenta");
    cbxServicios.addItem("Generar Tarjeta de Crédito");
    cbxServicios.addItem("Solicitar Préstamo");
    cbxServicios.updateUI();
    
    }
     public void poputTable() {
        JPopupMenu popuMenu = new JPopupMenu();
        JMenuItem menuItem1 = new JMenuItem("Agregar Turno");
        JMenuItem menuItem2 = new JMenuItem("Ver Turnos");
        menuItem1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frm_RegTicket ventanaT = new frm_RegTicket(new javax.swing.JDialog(), true);
                int fila = tblOficina.getSelectedRow();
                ventanaT.setVisible(true);
                

            }
        });
   
        popuMenu.add(menuItem1);

        tblOficina.setComponentPopupMenu(popuMenu);
    }
     public void guardar (){
         if (txtApeEncargado.getText().trim().isEmpty() || txtNomEncargado.getText().trim().isEmpty()) {
             JOptionPane.showMessageDialog(null, "Llene los campos vacíos", "Aviso", JOptionPane.INFORMATION_MESSAGE);
         }else{
         ofc.getOficina().setNomEncargado(txtNomEncargado.getText().trim());
         ofc.getOficina().setNomEncargado(txtApeEncargado.getText().trim());
         ofc.getOficina().setServicio(cbxServicios.getSelectedItem().toString());
             if (ofc.guardar(txtNomEncargado.getText().trim(), txtApeEncargado.getText().trim(), cbxServicios.getSelectedItem().toString())) {
                 JOptionPane.showMessageDialog(null, "Guardado", "Éxito", JOptionPane.INFORMATION_MESSAGE);
             }else{
             JOptionPane.showMessageDialog(null, "No se pudo guardar", "Error", JOptionPane.ERROR_MESSAGE);
             }
         
         }
         Limpiar();
     
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNomEncargado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApeEncargado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbxServicios = new javax.swing.JComboBox<>();
        btnOficina = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOficina = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Oficina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel3.setLayout(null);

        jLabel6.setText("Nombre Encargado:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 30, 130, 36);
        jPanel3.add(txtNomEncargado);
        txtNomEncargado.setBounds(158, 30, 180, 30);

        jLabel7.setText("Apellido Encargado:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 80, 140, 30);
        jPanel3.add(txtApeEncargado);
        txtApeEncargado.setBounds(160, 80, 170, 30);

        jLabel8.setText("Servicio:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(360, 30, 80, 30);

        cbxServicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(cbxServicios);
        cbxServicios.setBounds(420, 30, 170, 30);

        btnOficina.setText("Crear Oficina");
        btnOficina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOficinaActionPerformed(evt);
            }
        });
        jPanel3.add(btnOficina);
        btnOficina.setBounds(510, 80, 110, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 60, 670, 140);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entidades - Servicios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tblOficina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOficina);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 210, 670, 240);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("BANCO \"NARNIA\"");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(270, 20, 130, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 690, 470);

        setSize(new java.awt.Dimension(707, 478));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOficinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOficinaActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_btnOficinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Oficina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Oficina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Oficina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Oficina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_Oficina dialog = new frm_Oficina(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOficina;
    private javax.swing.JComboBox<String> cbxServicios;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOficina;
    private javax.swing.JTextField txtApeEncargado;
    private javax.swing.JTextField txtNomEncargado;
    // End of variables declaration//GEN-END:variables
}
