/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ejercicio2.vista;

/**
 *
 * @author Javier
 */
public class VentaTickets extends javax.swing.JDialog {

    /**
     * Creates new form VentaTickets
     */
    public VentaTickets(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPropietarioBanco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTelfBanco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDirBanco = new javax.swing.JTextField();
        btnBanco = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreEncargado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApeEncargado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Banco", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.setLayout(null);

        jLabel1.setText("Propietario:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(11, 27, 80, 16);
        jPanel2.add(txtPropietarioBanco);
        txtPropietarioBanco.setBounds(120, 20, 200, 30);

        jLabel2.setText("Dirección:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 70, 90, 16);
        jPanel2.add(txtTelfBanco);
        txtTelfBanco.setBounds(450, 20, 190, 30);

        jLabel3.setText("Telefono:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(384, 24, 60, 30);
        jPanel2.add(txtDirBanco);
        txtDirBanco.setBounds(130, 70, 190, 30);

        btnBanco.setText("Crear Banco");
        jPanel2.add(btnBanco);
        btnBanco.setBounds(520, 80, 110, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 20, 660, 120);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Oficina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel3.setLayout(null);

        jLabel4.setText("Encargado");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(11, 24, 90, 16);

        jLabel5.setText("Nombre:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(11, 52, 70, 16);
        jPanel3.add(txtNombreEncargado);
        txtNombreEncargado.setBounds(120, 40, 190, 30);

        jLabel6.setText("Apellido:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 90, 80, 16);
        jPanel3.add(txtApeEncargado);
        txtApeEncargado.setBounds(120, 90, 190, 30);

        jLabel7.setText("Servicio:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(340, 50, 70, 16);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(420, 40, 220, 30);

        jButton1.setText("Crear Oficina");
        jPanel3.add(jButton1);
        jButton1.setBounds(520, 100, 100, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 150, 660, 140);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 680, 300);

        setSize(new java.awt.Dimension(699, 343));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentaTickets dialog = new VentaTickets(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanco;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtApeEncargado;
    private javax.swing.JTextField txtDirBanco;
    private javax.swing.JTextField txtNombreEncargado;
    private javax.swing.JTextField txtPropietarioBanco;
    private javax.swing.JTextField txtTelfBanco;
    // End of variables declaration//GEN-END:variables
}
